import path from 'node:path';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { createDb } from './client';

/** Folder with the SQL migrations generated by drizzle-kit (shipped with the package). */
export const MIGRATIONS_FOLDER = path.resolve(__dirname, '..', 'drizzle');

export async function runMigrations(url: string): Promise<void> {
  const handle = createDb(url, { max: 1 });
  try {
    await migrate(handle.db, { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await handle.close();
  }
}
