import { z } from 'zod';
import type { Branding } from './branding';

/**
 * The public "Submit a request" form (channel `web_form`). Anyone can submit
 * it, so it is deliberately narrow: a new ticket every time, never access to
 * existing ones. Follow-ups happen by email, threaded on the ticket reference.
 */
export const WEB_FORM_MAX_FILES = 3;
export const WEB_FORM_MAX_FILE_BYTES = 10 * 1024 * 1024;

const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .optional()
    .transform((v) => v || undefined);

export const webFormSchema = z.object({
  /** Generated by the page once per form; a resubmit with the same id returns the same ticket. */
  submissionId: z.string().uuid(),
  name: z.string().trim().min(1, 'Enter your name').max(120),
  email: z.string().trim().email('Enter a valid email address').max(254),
  subject: z.string().trim().min(3, 'Add a short subject').max(200),
  description: z
    .string()
    .trim()
    .min(10, 'Describe the problem in a few words')
    .max(10_000, 'Keep the description under 10,000 characters'),
  categoryId: z
    .string()
    .uuid()
    .optional()
    .or(z.literal('').transform(() => undefined)),
  /** The form's optional reference field. Its label is a branding setting; the name is historic. */
  orderNumber: optionalText(60),
  /** Honeypot: hidden from people, so only bots fill it in. */
  website: z.string().max(0, 'Could not submit the form').optional(),
});
export type WebFormInput = z.input<typeof webFormSchema>;
export type WebForm = z.output<typeof webFormSchema>;

export interface WebFormConfig {
  categories: { id: string; name: string }[];
  maxFiles: number;
  maxFileBytes: number;
  /** Who the help center speaks for, and how the form's reference field is named. */
  branding: Branding;
}

export interface WebFormReceipt {
  /** Ticket reference, e.g. TMS-1042. */
  reference: string;
  /** Where the acknowledgement and replies go. */
  email: string;
}
